# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "tess")
    upload_to_testflight
  end
  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: "my_project.xcodeproj")
    build_app
    enable_automatic_code_signing(path: "my_project.xcodeproj")
    upload_to_testflight
  end
end
